# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 701)
        MainWindow.setStyleSheet("background-color: #8B008B;\n"
"border: 4px solid #4B0082;\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 481, 171))
        self.label.setStyleSheet("border: 4px solid black;\n"
"border-radius: 15px 15px;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("naruto-on-netflix.jpg"))
        self.label.setObjectName("label")
        self.title = QtWidgets.QLineEdit(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(40, 260, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setItalic(True)
        self.title.setFont(font)
        self.title.setStyleSheet("border: 4px solid #4B0082;\n"
"border-radius: 15px 15px 15px 15px;\n"
"background-color:#00BFFF;")
        self.title.setObjectName("title")
        self.date = QtWidgets.QLineEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(40, 400, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setItalic(True)
        self.date.setFont(font)
        self.date.setStyleSheet("border: 4px solid #4B0082;\n"
"border-radius: 15px 15px 15px 15px;\n"
"background-color:#00BFFF;")
        self.date.setObjectName("date")
        self.chapter = QtWidgets.QComboBox(self.centralwidget)
        self.chapter.setGeometry(QtCore.QRect(40, 190, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setItalic(True)
        self.chapter.setFont(font)
        self.chapter.setStyleSheet("border: 4px solid #4B0082;\n"
"border-radius: 15px 15px 15px 15px;\n"
"background-color:#00BFFF;")
        self.chapter.setIconSize(QtCore.QSize(20, 20))
        self.chapter.setObjectName("chapter")
        self.chapter.addItem("")
        self.chapter.addItem("")
        self.chapter.addItem("")
        self.chapter.addItem("")
        self.chapter.addItem("")
        self.genre = QtWidgets.QComboBox(self.centralwidget)
        self.genre.setGeometry(QtCore.QRect(40, 330, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setItalic(True)
        self.genre.setFont(font)
        self.genre.setStyleSheet("border: 4px solid #4B0082;\n"
"border-radius: 15px 15px 15px 15px;\n"
"background-color:#00BFFF;")
        self.genre.setIconSize(QtCore.QSize(20, 20))
        self.genre.setObjectName("genre")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.genre.addItem("")
        self.short_text = QtWidgets.QTextEdit(self.centralwidget)
        self.short_text.setGeometry(QtCore.QRect(40, 470, 401, 131))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setItalic(False)
        self.short_text.setFont(font)
        self.short_text.setStyleSheet("border: 4px solid #4B0082;\n"
"border-radius: 15px 15px 15px 15px;\n"
"background-color:#00BFFF;")
        self.short_text.setObjectName("short_text")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 610, 171, 61))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:#FF0000;\n"
"color: rgb(255, 255, 255);\n"
"border: 4px solid #4B0082;\n"
"border-radius: 15px 15px 15px 15px;")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setPlaceholderText(_translate("MainWindow", "   Введите название"))
        self.date.setPlaceholderText(_translate("MainWindow", "   Введите год"))
        self.chapter.setItemText(0, _translate("MainWindow", "    Выберите раздел"))
        self.chapter.setItemText(1, _translate("MainWindow", "Фильм "))
        self.chapter.setItemText(2, _translate("MainWindow", "Сериал"))
        self.chapter.setItemText(3, _translate("MainWindow", "Аниме"))
        self.chapter.setItemText(4, _translate("MainWindow", "Мультфильм"))
        self.genre.setItemText(0, _translate("MainWindow", "   Выберите жанр"))
        self.genre.setItemText(1, _translate("MainWindow", "Боевик"))
        self.genre.setItemText(2, _translate("MainWindow", "Фантастика"))
        self.genre.setItemText(3, _translate("MainWindow", "Триллер"))
        self.genre.setItemText(4, _translate("MainWindow", "Романтика"))
        self.genre.setItemText(5, _translate("MainWindow", "Детектив"))
        self.genre.setItemText(6, _translate("MainWindow", "Драма"))
        self.genre.setItemText(7, _translate("MainWindow", "Комедия"))
        self.short_text.setPlaceholderText(_translate("MainWindow", "   Введите краткую информацию о фильме"))
        self.pushButton.setText(_translate("MainWindow", "Сохранить"))
